# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions 

name: Build and deploy JAR app to Azure Web App - devnexus

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SanLinkedin'
          #slot-name: 'Production'
          publish-profile: '<publishData><publishProfile profileName="SanLinkedin - Web Deploy" publishMethod="MSDeploy" publishUrl="sanlinkedin.scm.azurewebsites.net:443" msdeploySite="SanLinkedin" userName="$SanLinkedin" userPWD="AQJ9ioE3y4TsS7lJaCO6CjOMA4ZosgE.wl6DpfWfLAE9ps2rOoJQ3L5I3x9zZMVHqyvQF2_k45o" destinationAppUrl="https://sanlinkedin.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="SanLinkedin - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-blu-249.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="SanLinkedin\$SanLinkedin" userPWD="AQJ9ioE3y4TsS7lJaCO6CjOMA4ZosgE.wl6DpfWfLAE9ps2rOoJQ3L5I3x9zZMVHqyvQF2_k45o" destinationAppUrl="https://sanlinkedin.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="SanLinkedin - Zip Deploy" publishMethod="ZipDeploy" publishUrl="sanlinkedin.scm.azurewebsites.net:443" userName="$SanLinkedin" userPWD="AQJ9ioE3y4TsS7lJaCO6CjOMA4ZosgE.wl6DpfWfLAE9ps2rOoJQ3L5I3x9zZMVHqyvQF2_k45o" destinationAppUrl="https://sanlinkedin.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>'
          package: '*.jar'
